language: python
python:
  - "3.6"
install:
  - pip install twine
script:
  - ./setup.py test
  - ./setup.py build sdist
  - twine check dist/*
deploy:
  provider: pypi
  user: pfariello
  password:
    secure: FC/U8R3Lo3cHNVQH40fW74lK1LKaWgtjn//0BDbMGaV2X7/cotcHpNLMC4iGj5nYorTaOUWFSXUL6MEWU7GTcUwSRCcTLLnJGdcMJKi/SINgzvat1Upi6TUp6bs3/ihhxXXImjTVkSk5o4S1hlCr5ZayXcfVMkj5/DeBX3YsAobApvxIJtGUMxE5pCYQtpSc0mgkUZuCzF65QmIGQMfZ5wHkKsOr9GFc78J5h5Uh0WeRQomIWqJUiX9sbS4SMJUXHNVfmUYe7tXlMO+WaNyd+9F4VY3VcwPtBdPbIowRF+FRExqNUDGUqt4hG9WgkcJiY+aF+/OL1BbmYXioo3zEPyHnb5UhIViG+FG7z25tRmGDeFBsEXKHG/e7CvQOoTkUkyx9wc0Y/f6cPAa/QrBAdX6dyulheO/a7M0XkJidA1DHPK7lpPRgge5yDQOAhiBCCuyKNEImEHpghPA0B0oUGMcS6xW3CqoxEvOEHZd+ARIqWrZGvoRziEVQojrn16XHHlinhpangnNq9TWZpcXicEV7bM4d+EbNrEyqoXpbexhdHhsQp4VEHCtC7sz1FCoGaacsM3KhqvGg74KUVOgz+E3knAAeDk53IbtnQz0fcOi2uYm5U6Cth1dmWYONzwNUt10tk/ToxGLrLHr7UIAIrpSFPWBAWmwuPI8zMuPRDSQ=
  on:
    tags: true
    python: "3.6"
  skip_existing: true
